services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: citydrop
      TZ: UTC
    volumes:
      - postgres-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-local: